name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'server/**'

jobs:
  backend-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      
